//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Typing.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRESO
    {
        public int ProgresoID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> PPMC { get; set; }
        public Nullable<int> Leccion { get; set; }
        public Nullable<int> Nivel { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
